//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleUser
    {
        public int Step { get; set; }
        public System.Guid Game { get; set; }
        public System.Guid BattleId { get; set; }
        public string HomeCardType { get; set; }
        public Nullable<int> Strength { get; set; }
        public string AdditionalEffect { get; set; }
        public Nullable<bool> IsWinner { get; set; }
        public Nullable<System.Guid> RandomDeskId { get; set; }
    
        public virtual Step Step1 { get; set; }
    }
}
