//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoType
    {
        public DoType()
        {
            this.OrderType = new HashSet<OrderType>();
        }
    
        public string Name { get; set; }
        public int Sort { get; set; }
    
        public virtual ICollection<OrderType> OrderType { get; set; }
    }
}
