//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePointType
    {
        public GamePointType()
        {
            this.GamePoint = new HashSet<GamePoint>();
        }
    
        public System.Guid Id { get; set; }
    
        public virtual ICollection<GamePoint> GamePoint { get; set; }
    }
}
