//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePoint
    {
        public GamePoint()
        {
            this.ObjectPoint = new HashSet<ObjectPoint>();
            this.TokenPoint = new HashSet<TokenPoint>();
            this.TrackPoint = new HashSet<TrackPoint>();
        }
    
        public System.Guid Id { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public System.Guid GamePointType { get; set; }
    
        public virtual GamePointType GamePointType1 { get; set; }
        public virtual ICollection<ObjectPoint> ObjectPoint { get; set; }
        public virtual ICollection<TokenPoint> TokenPoint { get; set; }
        public virtual ICollection<TrackPoint> TrackPoint { get; set; }
    }
}
