//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameUser
    {
        public GameUser()
        {
            this.Step = new HashSet<Step>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Game { get; set; }
        public string Login { get; set; }
        public string HomeType { get; set; }
        public System.DateTimeOffset LastUpdate { get; set; }
        public bool NeedReConnect { get; set; }
        public bool IsCapitulated { get; set; }
    
        public virtual Game Game1 { get; set; }
        public virtual HomeType HomeType1 { get; set; }
        public virtual ICollection<Step> Step { get; set; }
    }
}
