//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeType
    {
        public HomeType()
        {
            this.GameUser = new HashSet<GameUser>();
            this.HomeCardType = new HashSet<HomeCardType>();
        }
    
        public string Name { get; set; }
        public string Terrain { get; set; }
    
        public virtual ICollection<GameUser> GameUser { get; set; }
        public virtual ICollection<HomeCardType> HomeCardType { get; set; }
    }
}
