//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarchUnit
    {
        public System.Guid Id { get; set; }
        public int Step { get; set; }
        public System.Guid Game { get; set; }
        public System.Guid Unit { get; set; }
        public string Terrain { get; set; }
        public string UnitType { get; set; }
    
        public virtual March March { get; set; }
    }
}
