//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Agot2p6Entities : DbContext
    {
        public Agot2p6Entities()
            : base("name=Agot2p6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arrow> Arrow { get; set; }
        public virtual DbSet<Battle> Battle { get; set; }
        public virtual DbSet<BattleUser> BattleUser { get; set; }
        public virtual DbSet<DoType> DoType { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<GameException> GameException { get; set; }
        public virtual DbSet<GameInfo> GameInfo { get; set; }
        public virtual DbSet<GamePoint> GamePoint { get; set; }
        public virtual DbSet<GamePointType> GamePointType { get; set; }
        public virtual DbSet<GameUser> GameUser { get; set; }
        public virtual DbSet<GameUserInfo> GameUserInfo { get; set; }
        public virtual DbSet<GameUserTerrain> GameUserTerrain { get; set; }
        public virtual DbSet<Garrison> Garrison { get; set; }
        public virtual DbSet<HomeCardType> HomeCardType { get; set; }
        public virtual DbSet<HomeType> HomeType { get; set; }
        public virtual DbSet<March> March { get; set; }
        public virtual DbSet<MarchUnit> MarchUnit { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<ObjectPoint> ObjectPoint { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderType> OrderType { get; set; }
        public virtual DbSet<PowerCounter> PowerCounter { get; set; }
        public virtual DbSet<Raid> Raid { get; set; }
        public virtual DbSet<RandomDesk> RandomDesk { get; set; }
        public virtual DbSet<Raven> Raven { get; set; }
        public virtual DbSet<Step> Step { get; set; }
        public virtual DbSet<StepType> StepType { get; set; }
        public virtual DbSet<Support> Support { get; set; }
        public virtual DbSet<Symbolic> Symbolic { get; set; }
        public virtual DbSet<Terrain> Terrain { get; set; }
        public virtual DbSet<TerrainTerrain> TerrainTerrain { get; set; }
        public virtual DbSet<TerrainType> TerrainType { get; set; }
        public virtual DbSet<TokenPoint> TokenPoint { get; set; }
        public virtual DbSet<TokenType> TokenType { get; set; }
        public virtual DbSet<TrackPoint> TrackPoint { get; set; }
        public virtual DbSet<TrackType> TrackType { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<UnitType> UnitType { get; set; }
        public virtual DbSet<UsedHomeCard> UsedHomeCard { get; set; }
        public virtual DbSet<VesterosAction> VesterosAction { get; set; }
        public virtual DbSet<VesterosActionType> VesterosActionType { get; set; }
        public virtual DbSet<VesterosCardAction> VesterosCardAction { get; set; }
        public virtual DbSet<VesterosCardType> VesterosCardType { get; set; }
        public virtual DbSet<VesterosDecks> VesterosDecks { get; set; }
        public virtual DbSet<Voting> Voting { get; set; }
    }
}
