//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid Id { get; set; }
        public int Step { get; set; }
        public System.Guid Game { get; set; }
        public System.Guid FirstId { get; set; }
        public string OrderType { get; set; }
        public string Terrain { get; set; }
    
        public virtual GameUserInfo GameUserInfo { get; set; }
        public virtual OrderType OrderType1 { get; set; }
        public virtual Terrain Terrain1 { get; set; }
    }
}
