//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public Step()
        {
            this.Arrow = new HashSet<Arrow>();
            this.Message = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public System.Guid Game { get; set; }
        public System.Guid GameUser { get; set; }
        public string StepType { get; set; }
        public bool IsFull { get; set; }
    
        public virtual ICollection<Arrow> Arrow { get; set; }
        public virtual BattleUser BattleUser { get; set; }
        public virtual GameInfo GameInfo { get; set; }
        public virtual GameUser GameUser1 { get; set; }
        public virtual GameUserInfo GameUserInfo { get; set; }
        public virtual March March { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual Raid Raid { get; set; }
        public virtual Raven Raven { get; set; }
        public virtual StepType StepType1 { get; set; }
        public virtual Support Support { get; set; }
        public virtual VesterosAction VesterosAction { get; set; }
        public virtual Voting Voting { get; set; }
    }
}
