//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepType
    {
        public StepType()
        {
            this.Step = new HashSet<Step>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<Step> Step { get; set; }
    }
}
