//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenType
    {
        public TokenType()
        {
            this.Garrison = new HashSet<Garrison>();
            this.OrderType = new HashSet<OrderType>();
            this.PowerCounter = new HashSet<PowerCounter>();
            this.TokenPoint = new HashSet<TokenPoint>();
            this.UnitType = new HashSet<UnitType>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<Garrison> Garrison { get; set; }
        public virtual ICollection<OrderType> OrderType { get; set; }
        public virtual ICollection<PowerCounter> PowerCounter { get; set; }
        public virtual ICollection<TokenPoint> TokenPoint { get; set; }
        public virtual ICollection<UnitType> UnitType { get; set; }
    }
}
