//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackPoint
    {
        public System.Guid Id { get; set; }
        public string TrackType { get; set; }
        public int Value { get; set; }
        public System.Guid GamePoint { get; set; }
    
        public virtual GamePoint GamePoint1 { get; set; }
        public virtual TrackType TrackType1 { get; set; }
    }
}
