//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedHomeCard
    {
        public int Step { get; set; }
        public System.Guid Game { get; set; }
        public string HomeCardType { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual GameUserInfo GameUserInfo { get; set; }
        public virtual HomeCardType HomeCardType1 { get; set; }
    }
}
