//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class VesterosCardType
    {
        public VesterosCardType()
        {
            this.VesterosCardAction = new HashSet<VesterosCardAction>();
            this.VesterosDecks = new HashSet<VesterosDecks>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public int DecksNumber { get; set; }
        public bool BarbarianFlag { get; set; }
        public string Description { get; set; }
        public int Count { get; set; }
        public int PlayCount { get; set; }
    
        public virtual ICollection<VesterosCardAction> VesterosCardAction { get; set; }
        public virtual ICollection<VesterosDecks> VesterosDecks { get; set; }
    }
}
