//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiUser
    {
        public string uid { get; set; }
        public bool isFacebook { get; set; }
        public string Login { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string photo { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTimeOffset> LastConnection { get; set; }
        public string ClientId { get; set; }
        public string resetPswCode { get; set; }
        public Nullable<System.DateTimeOffset> resetPswDate { get; set; }
        public bool emailConfirm { get; set; }
    
        public virtual User User { get; set; }
    }
}
