//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialUser
    {
        public string Login { get; set; }
        public string SpecialLogin { get; set; }
        public bool IsBlock { get; set; }
    
        public virtual User User { get; set; }
    }
}
