//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ApiUsers = new HashSet<ApiUser>();
            this.Payments = new HashSet<Payment>();
            this.SpecialUsers = new HashSet<SpecialUser>();
            this.Titles = new HashSet<Title>();
            this.UserGames = new HashSet<UserGame>();
            this.UserLikes = new HashSet<UserLike>();
        }
    
        public string Login { get; set; }
        public string Password { get; set; }
        public bool IsIgnore { get; set; }
        public System.Guid Version { get; set; }
    
        public virtual ICollection<ApiUser> ApiUsers { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<SpecialUser> SpecialUsers { get; set; }
        public virtual ICollection<Title> Titles { get; set; }
        public virtual ICollection<UserGame> UserGames { get; set; }
        public virtual ICollection<UserLike> UserLikes { get; set; }
    }
}
