//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGame
    {
        public System.Guid Id { get; set; }
        public string Login { get; set; }
        public System.Guid GameId { get; set; }
        public int GameType { get; set; }
        public string HomeType { get; set; }
        public System.DateTimeOffset StartTime { get; set; }
        public Nullable<System.DateTimeOffset> EndTime { get; set; }
        public int HonorPosition { get; set; }
        public bool IsIgnoreHonor { get; set; }
        public int MindPosition { get; set; }
        public bool IsIgnoreMind { get; set; }
        public bool IsIgnoreDurationHours { get; set; }
    
        public virtual User User { get; set; }
    }
}
