//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battle
    {
        public System.Guid Id { get; set; }
        public int Step { get; set; }
        public System.Guid Game { get; set; }
        public string AttackTerrain { get; set; }
        public string DefenceTerrain { get; set; }
        public System.Guid AttackUser { get; set; }
        public System.Guid DefenceUser { get; set; }
    
        public virtual GameInfo GameInfo { get; set; }
    }
}
