//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfo
    {
        public GameInfo()
        {
            this.Garrison = new HashSet<Garrison>();
            this.VesterosDecks = new HashSet<VesterosDecks>();
        }
    
        public int Step { get; set; }
        public System.Guid Game { get; set; }
        public int Turn { get; set; }
        public int Barbarian { get; set; }
    
        public virtual Battle Battle { get; set; }
        public virtual Step Step1 { get; set; }
        public virtual ICollection<Garrison> Garrison { get; set; }
        public virtual ICollection<VesterosDecks> VesterosDecks { get; set; }
    }
}
