//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameException
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Game { get; set; }
        public string Login { get; set; }
        public string Message { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsFull { get; set; }
    }
}
