//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class March
    {
        public March()
        {
            this.MarchUnit = new HashSet<MarchUnit>();
        }
    
        public int Step { get; set; }
        public System.Guid Game { get; set; }
        public string SourceOrder { get; set; }
        public bool IsTerrainHold { get; set; }
    
        public virtual Step Step1 { get; set; }
        public virtual ICollection<MarchUnit> MarchUnit { get; set; }
    }
}
