//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderType
    {
        public OrderType()
        {
            this.Order = new HashSet<Order>();
        }
    
        public string Name { get; set; }
        public string TokenType { get; set; }
        public bool IsSpecial { get; set; }
        public int Strength { get; set; }
        public int Count { get; set; }
        public string DoType { get; set; }
    
        public virtual DoType DoType1 { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual TokenType TokenType1 { get; set; }
    }
}
