//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandomDesk
    {
        public System.Guid Id { get; set; }
        public int Strength { get; set; }
        public bool Attack { get; set; }
        public bool Defence { get; set; }
        public bool Skull { get; set; }
        public int PlayCount { get; set; }
        public string fileName { get; set; }
    }
}
