//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terrain
    {
        public Terrain()
        {
            this.GameUserTerrain = new HashSet<GameUserTerrain>();
            this.Garrison = new HashSet<Garrison>();
            this.ObjectPoint = new HashSet<ObjectPoint>();
            this.Order = new HashSet<Order>();
            this.PowerCounter = new HashSet<PowerCounter>();
            this.TerrainTerrain = new HashSet<TerrainTerrain>();
            this.TerrainTerrain1 = new HashSet<TerrainTerrain>();
            this.TokenPoint = new HashSet<TokenPoint>();
            this.Unit = new HashSet<Unit>();
        }
    
        public string Name { get; set; }
        public string TerrainType { get; set; }
        public int Supply { get; set; }
        public int Power { get; set; }
        public int Strength { get; set; }
    
        public virtual ICollection<GameUserTerrain> GameUserTerrain { get; set; }
        public virtual ICollection<Garrison> Garrison { get; set; }
        public virtual ICollection<ObjectPoint> ObjectPoint { get; set; }
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<PowerCounter> PowerCounter { get; set; }
        public virtual ICollection<TerrainTerrain> TerrainTerrain { get; set; }
        public virtual TerrainType TerrainType1 { get; set; }
        public virtual ICollection<TerrainTerrain> TerrainTerrain1 { get; set; }
        public virtual ICollection<TokenPoint> TokenPoint { get; set; }
        public virtual ICollection<Unit> Unit { get; set; }
    }
}
