//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackType
    {
        public TrackType()
        {
            this.TrackPoint = new HashSet<TrackPoint>();
        }
    
        public string Name { get; set; }
    
        public virtual ICollection<TrackPoint> TrackPoint { get; set; }
    }
}
