//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitType
    {
        public UnitType()
        {
            this.Unit = new HashSet<Unit>();
        }
    
        public string Name { get; set; }
        public string TokenType { get; set; }
        public int Strength { get; set; }
        public int Cost { get; set; }
        public int Count { get; set; }
    
        public virtual TokenType TokenType1 { get; set; }
        public virtual ICollection<Unit> Unit { get; set; }
    }
}
